name = "Hugoplate"
license = "MIT"
licenselink = "https://github.com/haloorderio/hugoplate/blob/main/LICENSE"
description = "A minimal, responsive and customizable theme for Hugo."
homepage = "https://github.com/haloorderio/hugoplate"
tags = ["blog", "portfolio", "minimal"]
features = ["responsive", "minimal", "customizable"]
min_version = "0.62.0"

[author]
  name = "Hugoplate Team"
  homepage = "https://github.com/haloorderio"

# Additional configuration options can go here
